---
# tasks file for lamp
- name: install httpd
  yum:
    name: httpd
    state: latest

- name: install php packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - php
    - php-common
    - php-opcache
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd
    - php-mysqli

- name: create index.php file from template
  template:
    src: source/index.php.j2
    dest: /var/www/html/index.php

- name: copy create php files
  copy:
    src: source/process_create.php
    dest: /var/www/html

- copy:
    src: source/create.php
    dest: /var/www/html
